### ISSUE TITLE
Text missing in aorsa2d.ps

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#32]
It seems that the ps lost all text. When I ran AORSA back in May all the graphs in aorsa2d.ps had labels, but they are all gone in the file from my 128 MHz helicon computation (I repeated it today). The old aorsa2d.ps is also two times larger.
I checked the file with 3 viewers: Ghostviewer on windows, acrobat distiller on windows, and ghost viewer on windows subsystem Linux.
Maybe it is necessary to recompile pgplot?

I am not sure whether I want to submit my full-scale AORSA calculation now, since I only know how to diagnose my AORSA runs with these plots.

Any advice would be helpful.

I attached all the usual output and the PDF I got from acrobat distiller, since PS is not supported here. I also attached the first 11 pages from the AORSA run I did in May. 

[log_aorsa2d.txt](https://github.com/ORNL-Fusion/aorsa/files/5138379/log_aorsa2d.txt)
[out15.txt](https://github.com/ORNL-Fusion/aorsa/files/5138358/out15.txt)
[aorsa2d_in.txt](https://github.com/ORNL-Fusion/aorsa/files/5138383/aorsa2d_in.txt)
[aorsa2d.PDF](https://github.com/ORNL-Fusion/aorsa/files/5138360/aorsa2d.PDF)
[aorsa2d_may_excerpt.PDF](https://github.com/ORNL-Fusion/aorsa/files/5138372/aorsa2d_may_excerpt.PDF)

**Comment by dlg0** [comment]
This may be an issue with the `grfont.dat` file being missing? It is in the examples, but double check it is still present in your run directory.

**Comment by AreWeDreaming** [comment]
That makes sense, thanks! Rerunning the debug case now!

**Comment by AreWeDreaming** [comment]
Ok that fixed it. Thanks! I will keep in mind that I have to have that file in my working directory.
