### ISSUE TITLE
Moving the boundary in flux surface bound calculation

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#39]
I performed a scan on the antenna position with AORSA. When moving the antenna away from the boundary I noticed that I get a lot less spurious modes in the calculation. This also removes the noise from `ntilda`. However, as a side effect, this causes a second beam to be created due to power being reflected back from the boundary into the plasma (see [Re_E_alpha.pdf](https://github.com/ORNL-Fusion/aorsa/files/5655287/Re_E_alpha.pdf)).

To compensate for this I set `psilim`=`psiant`=0.85, which yielded a clean simulation without any noise in `ntilda` and no discernible second beam.

However, since `psilim` is just psi at the separatrix and it does not define the boundary directly. This leads to some other strange features as I reported in #35.

So the question that I have is there any way I can move the boundary inwards properly?

Please note that I still have a lot of CPU time to spend on NERSC (8 million hours), and each week that passes without any replies, it becomes more and more unlikely that I can deplete my account before the end of December.

**Comment by cornwalllau** [comment]
Have you looked into the keyword rhomax? I'm not sure if it's what you are looking for, but it's something to try?

**Comment by AreWeDreaming** [comment]
Yeah I tried that at low resolution and as far as I could tell it did nothing. The only thing that moved the boundary in the plots was `psilim`.

**Comment by cornwalllau** [comment]
Ok. It's possible that psilim < value, then AORSA calculates the hot kinetic terms for psilim < value and the cold terms for psilim > value. Let me send an email to Fred Jaeger and I'll see what he says.

**Comment by cornwalllau** [comment]
Ok, so Fred thinks psilim used to be the boundary of the metal wall, but he doesn't remember exactly and has not accessed NERSC in a long time. Given he is retired for a few years now, I don't want to push further. 

If you are running out of things to try to change boundary conditions, you can turn the SOL on while keeping the antenna inside the LCFS. See some of the keywords in https://github.com/ORNL-Fusion/aorsa/blob/master/examples/DIIID-helicon/aorsa2d.in such as nboundary, nmin, scrape. Note I have only tried these SOL cases with antenna outside the LCFS and it's a hit or miss (mostly misses...) so it might be numerically troublesome but given you have some run time and you are out of ideas, it could be worth a try...

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
