### ISSUE TITLE
AORSA scaling

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#41]
I have tried to run the DIII-D shot 165908, which is the demonstration case for off-axis helicon heating.
This shot has only 1.5 T magnetic field resulting in very large k_perp. I first ran the case at 2.0 T to establish the resolution needed for that case. I ended up with 512x360, which is large, but without wdot it can be handled by 288 nodes in 130 minutes total.
Using the cold plasma dispersion relation I estimated that I need to increase the resolution to 768x432 to get a converged case at 1.5 T. 
Assuming that solving the matrix equation scales with N^3 (N=nmodesx*nmodesy) I assumed that the CPU time would increase by 1.8^3=5.83. Accordingly, I assigned 1152 nodes for the task which was an increase in the number of cores by a factor of 4. 
Since the original calculation took 130 minutes, one would expect this task to run for 130 * 5.83 / 4 = 190 minutes. 
Unfortunately, the task timed out after 12 h giving me no information on how long SCALAPACK really needs to invert this matrix.
When I fit T = A*N^n  with T  the minutes scalapack needs times the number of processors used to my previous runs I get n=3.2. If I extrapolate from that the 36864 CPUs that I am using should have solved this problem in about 100 minutes << than the 450+ that it did use. Please note that assembling the matrix took already 128 minutes. This is the one piece of information I learned from this attempt. This seems to scale with the square of the grid size.

So the questions here are:
a) Does anybody know what is happening here?
b) Do you have tips on how I can diagnose this without wasting another 1.5 million CORI hours?

**Comment by cornwalllau** [comment]
I cannot give you a really good answer. I do know that the highest Fred and I went is 600x600 grid size here. It wasn't easy going from 400x400 to 600x600, but I can't remember what were the issues. You might have to go step by step if that is what you need..

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
