### ISSUE TITLE
Normalizing AORSA calculations

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#42]
So far I have been using a volume integration over wdot_tot from the Efield_2D.vtk file to renormalize all quantities computed by AORSA. Now I am not so sure anymore if this is actually the correct way of doing things.
From AORSA I get this:
```
 Species absorption from Estar dot J:
         power absorbed by electrons = 0.84159E+06 Watts  =    84.1590 %       
     power absorbed by majority ions = 0.15841E+06 Watts  =    15.8410 % 
 Species absorption from Wdot:
         power absorbed by electrons = 0.35175E+06 Watts  =   100.0000 %  
Species absorption from quasilinear Wdot:
         power absorbed by electrons = 0.58096E+06 Watts  =   100.0000 % 
```
I know that Estar dot J is not good, but then there are two wdots out there, only one of which ends up in the .vtk file.
Is the wdot_tot in the .vtk File even in W/m^-3?
This inquiry is motivated by us getting vastly different density fluctuations between the cold plasma approximations and AORSA.

**Comment by AreWeDreaming** [comment]
Follow-up comment.
I looked in the source code and it looks like per default everything is normalized to 1/2Re(E . J) which means I definitely need to do some renormalizing.
I found the spot in the code, where the different total absorptions are calculated, but I do not understand the integration itself.
In `sgrator` in `aorsaSubs.f` it looks a simple 2D rectangular integration is done, but in the end, the result is divided by the major radius: `ans = ans / r0`. I implemented the same integration in Python using `wdot_tot` and I get values completely different from the out15 file.

**Comment by ntsujii** [comment]
Hi Severin,

As long as the solution is well converged, EdotJ and the two wdot's should give you approximately the same numbers for the global power, although the local profile of EdotJ can oscillate wildly in certain scenarios. wdot and wdot_ql are really the same thing (just summed over in different orders, basically). I have renormalized the field with wdot in the past in mode conversion scenarios (not an easy scenario), but the results weren't that much different from the original normalization. So if you are seeing very different numbers for those global powers, you should first do a convergence test. (Do you get the same results when you increase the resolution? What about the wavenumber spectrum?)

Regarding density fluctuations, you should not use cold plasma for analysis in fusion grade experiments. ntilde is proportional to what corresponds to the Stix 'P' component of the dielectric tensor, which is hot. If you use cold, you may well be off by an order of magnitude depending of the electron temperature and N_parallel.

Naoto

**Comment by cornwalllau** [comment]
Just to make sure, I assume you had already checked that the spatial integral of Wdot you have in the Efield2D.vtk file does not match the AORSA2D out15 file output for the total power?

It's been too long since I used AORSA, but it's worth checking this spatial integral above assuming units are W/m^3, ergs/cm^3, W/m^2, ergs/cm^2. I suspect Fred Jaeger went with SI units; he usually does. I honestly do not remember if it is W/m^2 or W/m^3; it could be either depending on Fred's choice of convention.

Naoto: for the helicon problem, we had to use artificial damping terms for numerical convergence. Fred said this was rarely necessary for ICRF stuff and he said for reasons I do not understand, the artificial damping only appeared in E dot J and does not appear in Wdot. Therefore, Wdot had more accurate power absorption for the helicon problem.  I do agree with you about the the difference between cold and hot plasma. It is certainly not obvious to me why they should be close.

**Comment by ntsujii** [comment]
Ah.., I see. From my vague memory, wasn't there an attempt to include the artificial damping in wdot? It was not a trivial fix, but I remember Fred presenting something somewhere (sorry, just can't remember the details).

**Comment by cornwalllau** [comment]
I don't recall that detail myself on artificial damping in wdot. It has also been a long time for me too...

**Comment by AreWeDreaming** [comment]
I don't think the difference between `Wdot `and the `quasilinear Wdot` is a convergence problem. My Fourier spectra look really good and also the density fluctuations aren't noisy at all. Nevertheless, I will do a quick convergence test.

Anticipating hot plasma effects, I have also tried using the hot plasma conductivity tensor I get from the forest.f routine in GENRAY to post-process my COMSOL results. This is based on the hot dielectric tensor from Stix. I am not entirely sure how this compares to the dielectric tensor in AORSA. The main distinction that I understand is that the forest routine uses geometrical optics to compute the tensor by solving the hot plasma dispersion relation.
The density fluctuations resulting from this conductivity tensor are comparable to the ones from the cold dielectric tensor. Notably, it seems that the contribution from the P term seems to be rather weak for helicon. I am now computing the electric fields from AORSA in lab-frame to see if the polarization between AORSA and COMSOL is vastly different and the cold plasma approximation underestimates the e_z (Stix frame) component.

Does anybody else have a comment on the `wdot_tot` integration in AORSA. The values I get from out15 do not match what I get when I manually and analogously integrate `wdot_tot` in python.

**Comment by dlg0** [comment]
On the integration, what volume element are you using in your own calculation? The aorsa integration is likely including the appropriate volume element / jacobian for its coordinate system (which I don't recall exactly what that was offhand). The 1/r may be that volume element?

**Comment by dlg0** [comment]
Regarding your "hot" dielectric post processing of the comsol results, you're using a single k (from the dispersion relation), so you might want to plot the dispersion relation determined kper v kpar over the aorsa spectrum of the same to see how well they match. I'd think for helicon the wave field structure isn't that different, just the damping, so you may way to compare both the real and imaginary versions of the plot I'd suggested.

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
