### ISSUE TITLE
AORSA memory requirements

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#43]
It seems that the memory requirements of the wdot calculations went up significantly after I recompiled AORSA. Is it expected that the wdot calculation (with nzeta_wdote = 51, nzeta_wdoti = 0), consumes (a lot) more memory than ScaLAPACK?

My last AORSA calculation on 288 nodes with a 448x448 grid died with OUT_OF_MEMORY with the last log entries:
 ```
xjx_max =   3.435404960082567E-008
 xjy_max =    322.488306213783     
 xjz_max =   0.000000000000000E+000
 xkprl_max =    169.774443965673     
 xkprl_pos_min =   0.272853307515924     
 xkprl_neg_max =  -0.272900817877951     
 xkprl_min =   -110.200249742706     
time to calculate currents =    1.048 min
```
In the past, I have done calculations with a 384x384 grid 128 nodes, but this also produces the same OUT_OF_MEMROY errr now.
The problem is that the AORSA does not scale linearly, so the more nodes I assign the lower the performance of ScaLAPACK. E.g. 16.198 GFlops on 128 nodes and 13.515 on 288.

My NERSC allocation is much smaller this year, so it is important to squeeze as much performance out of my hours as possible. Any suggestions?

**Comment by AreWeDreaming** [comment]
On second thought, I am not even sure if this is truly a memory issue,
AORSA dies with a `Bus error` which can be indicative of a memory issue. However, the MaxRSS size is not too large:
```
Failed job, m = 88
JobID            MaxRSS 
------------ ---------- 
60355861                
60355861.ba+      0.02G 
60355861.ex+      0.00G 
60355861.0        2.17G 
```
Successful job, m = 89
```
JobID            MaxRSS 
------------ ---------- 
60355842                
60355842.ba+      0.02G 
60355842.ex+      0.00G 
60355842.0        2.43G 
```
This MaxRSS is about half of the 4 GB theoretically available for each job.
I also created a 170x170 debug job that I ran on just 4 nodes:
```
JobID            MaxRSS 
------------ ---------- 
60599755                
60599755.ba+      0.02G 
60599755.ex+      0.00G 
60599755.0        2.69G
```
This has a higher RSS than any of the jobs above and works just fine.
I then put in a stop statement at the point where my large job crashes to check the RSS up to that point.
```
JobID            MaxRSS 
------------ ---------- 
60601180                
60601180.ba+      0.02G 
60601180.ex+      0.00G 
60601180.0        2.53G  
```
So for the steps beyond the crashing point just add a measly 0.04 GB, which matches my expectation of the allocation calls in `aorsa2dMain.F` in the lines `7869-7891`. The code that crashes is somewhere in between lines `7774-8817` in `aorsa2dMain.F`.  I found an MKL call to `blacs_barrier` and a SCALAPACK call `dgsum2d` in `ql_myra.f`. Besides that, the only other potential problem points are `besjc` and `z_approx` in `wdot_sum.f90` which I could not immediately track down in the source code.
I'll add some more print statements to this code section and then rerun the failing run. That'll help us track down the issue a lot better.

**Comment by jcwright77** [comment]
weird
sounds like a compiler issue. Possible from linking in a library that has not
been updated on cori.

-john

On Tue, June 28, 2022 3:26 pm, Severin Denk wrote:
> On second thought, I am not even sure if this is truly a memory issue,
> AORSA dies with a `Bus error` which can be indicative of a memory issue.
> However, the MaxRSS size is not too large:
> ```
> Failed job, m = 88
> JobID            MaxRSS
> ------------ ----------
> 60355861
> 60355861.ba+      0.02G
> 60355861.ex+      0.00G
> 60355861.0        2.17G
> ```
> Successful job, m = 89
> ```
> JobID            MaxRSS
> ------------ ----------
> 60355842
> 60355842.ba+      0.02G
> 60355842.ex+      0.00G
> 60355842.0        2.43G
> ```
> This MaxRSS is about half of the 4 GB theoretically available for each job.
> I also created a 170x170 debug job that I ran on just 4 nodes:
> ```
> JobID            MaxRSS
> ------------ ----------
> 60599755
> 60599755.ba+      0.02G
> 60599755.ex+      0.00G
> 60599755.0        2.69G
> ```
> This has a higher RSS than any of the jobs above and works just fine.
> I then put in a stop statement at the point where my large job crashes to
> check the RSS up to that point.
> ```
> JobID            MaxRSS
> ------------ ----------
> 60601180
> 60601180.ba+      0.02G
> 60601180.ex+      0.00G
> 60601180.0        2.53G
> ```
> So for the steps beyond the crashing point just add a measly 0.04 GB, which
> matches my expectation of the allocation calls in `aorsa2dMain.F` in the lines
> `7869-7891`. The code that crashes is somewhere in between lines `7774-8817`
> in `aorsa2dMain.F`.  I found an MKL call to `blacs_barrier` and a SCALAPACK
> call `dgsum2d` in `ql_myra.f`. Besides that, the only other potential problem
> points are `besjc` and `z_approx` in `wdot_sum.f90` which I could not
> immediately track down in the source code.
> I'll add some more print statements to this code section and then rerun the
> failing run. That'll help us track down the issue a lot better.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ORNL-Fusion/aorsa/issues/43#issuecomment-1169141480
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>


-- 
Principal Research Scientist John Wright
Office 617-253-9612
zoom: https://mit.zoom.us/my/jcwright

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
